/**
 * Whitelist of valid registrants for Cabisino 2026.
 * Each entry is "Vorname Nachname" — matching is case-insensitive and trimmed.
 * Replace or extend this list as needed.
 */
export const ALLOWED_NAMES: string[] = [
  "Alina Folmer",
  "Amelie Hilbrands",
  "Anja Gröger Valdez",
  "Ate Veenstra",
  "Celina Jütting",
  "Charlotte Weber",
  "Claas Frerichs",
  "Danilo Schuster",
  "Donata Linde",
  "Elias Kohn",
  "Ellen Cammenga",
  "Elsa Bunjes",
  "Enie Wichert",
  "Enno Leemhuis",
  "Eric Schön",
  "Erik Slacki",
  "Fabia Runde",
  "Femke Lüning",
  "Finja Heisig",
  "Gesa Wenninga",
  "Hanna Geiten",
  "Hanno Rademacher",
  "Hanno Steffen",
  "Henry Ulferts",
  "Imke Meints",
  "Jan Eden",
  "Jan-Renke de Vries",
  "Janko Wulf",
  "Jannes Lehmann",
  "Jannik Peters",
  "Jara Lünemann",
  "Jenola Feith",
  "Jerrick Hinrichs",
  "Joris Thelle",
  "Jule Schilling",
  "Jule Vogt",
  "Julia van der Zijl",
  "Julian Redetzky",
  "Kea Wilshusen",
  "Kristin Metz",
  "Lammert Tergast",
  "Lana Wilken",
  "Lara Malchus",
  "Leni Hickmann",
  "Lennart Lauts",
  "Leon Wenke",
  "Louisa Cristal",
  "Marie Spekker",
  "Marit Wolters",
  "Mattis Bunger",
  "Max Willers",
  "Maximilian Buse",
  "Mette Hajen",
  "Nike Janisch",
  "Noah Baumann",
  "Patricia Ruberg",
  "Rieka Bünting",
  "Rieke Goemann",
  "Ritika Singh",
  "Ruben Doosje",
  "Sarah Schlitt",
  "Sophia Beck",
  "Sophia Pham Thi",
  "Theo Halm",
  "Thies Groenewold",
  "Thore Daatmeyer",
  "Tino Brinker",
  "Tomke Eden",
  "Viktor Scholz",
  "Wiebke Straat",
  "Zino Ley",
  "Zoe Kunanz",
];

/**
 * Returns true if the given vorname + nachname combo is in the whitelist.
 * Comparison is case-insensitive and trims whitespace.
 */
export function isAllowed(vorname: string, nachname: string): boolean {
  const full = `${vorname.trim()} ${nachname.trim()}`.toLowerCase();
  return ALLOWED_NAMES.some((n) => n.toLowerCase() === full);
}
